namespace WindowsFormsApp1
{
    partial class calisanCikar
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(calisanCikar));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuLabelCalisanTc = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuTextBoxCalisanTc = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuButtonAra = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButtonTumu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButtonCalisanCikar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuLabelCalisanTc
            // 
            this.bunifuLabelCalisanTc.AllowParentOverrides = false;
            this.bunifuLabelCalisanTc.AutoEllipsis = false;
            this.bunifuLabelCalisanTc.AutoSize = false;
            this.bunifuLabelCalisanTc.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabelCalisanTc.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabelCalisanTc.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabelCalisanTc.Location = new System.Drawing.Point(32, 12);
            this.bunifuLabelCalisanTc.Name = "bunifuLabelCalisanTc";
            this.bunifuLabelCalisanTc.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabelCalisanTc.Size = new System.Drawing.Size(85, 37);
            this.bunifuLabelCalisanTc.TabIndex = 9;
            this.bunifuLabelCalisanTc.TabStop = false;
            this.bunifuLabelCalisanTc.Text = "Çalışan TC No:";
            this.bunifuLabelCalisanTc.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuLabelCalisanTc.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuTextBoxCalisanTc
            // 
            this.bunifuTextBoxCalisanTc.AcceptsReturn = false;
            this.bunifuTextBoxCalisanTc.AcceptsTab = false;
            this.bunifuTextBoxCalisanTc.AnimationSpeed = 200;
            this.bunifuTextBoxCalisanTc.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxCalisanTc.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxCalisanTc.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBoxCalisanTc.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxCalisanTc.BackgroundImage")));
            this.bunifuTextBoxCalisanTc.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxCalisanTc.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxCalisanTc.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxCalisanTc.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxCalisanTc.BorderRadius = 1;
            this.bunifuTextBoxCalisanTc.BorderThickness = 1;
            this.bunifuTextBoxCalisanTc.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxCalisanTc.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxCalisanTc.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBoxCalisanTc.DefaultText = "";
            this.bunifuTextBoxCalisanTc.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxCalisanTc.HideSelection = true;
            this.bunifuTextBoxCalisanTc.IconLeft = null;
            this.bunifuTextBoxCalisanTc.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxCalisanTc.IconPadding = 10;
            this.bunifuTextBoxCalisanTc.IconRight = null;
            this.bunifuTextBoxCalisanTc.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxCalisanTc.Lines = new string[0];
            this.bunifuTextBoxCalisanTc.Location = new System.Drawing.Point(123, 12);
            this.bunifuTextBoxCalisanTc.MaxLength = 32767;
            this.bunifuTextBoxCalisanTc.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxCalisanTc.Modified = false;
            this.bunifuTextBoxCalisanTc.Multiline = false;
            this.bunifuTextBoxCalisanTc.Name = "bunifuTextBoxCalisanTc";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxCalisanTc.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxCalisanTc.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxCalisanTc.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxCalisanTc.OnIdleState = stateProperties4;
            this.bunifuTextBoxCalisanTc.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxCalisanTc.PasswordChar = '\0';
            this.bunifuTextBoxCalisanTc.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxCalisanTc.PlaceholderText = "Çalışan Tc";
            this.bunifuTextBoxCalisanTc.ReadOnly = false;
            this.bunifuTextBoxCalisanTc.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxCalisanTc.SelectedText = "";
            this.bunifuTextBoxCalisanTc.SelectionLength = 0;
            this.bunifuTextBoxCalisanTc.SelectionStart = 0;
            this.bunifuTextBoxCalisanTc.ShortcutsEnabled = true;
            this.bunifuTextBoxCalisanTc.Size = new System.Drawing.Size(260, 37);
            this.bunifuTextBoxCalisanTc.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBoxCalisanTc.TabIndex = 0;
            this.bunifuTextBoxCalisanTc.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxCalisanTc.TextMarginBottom = 0;
            this.bunifuTextBoxCalisanTc.TextMarginLeft = 3;
            this.bunifuTextBoxCalisanTc.TextMarginTop = 0;
            this.bunifuTextBoxCalisanTc.TextPlaceholder = "Çalışan Tc";
            this.bunifuTextBoxCalisanTc.UseSystemPasswordChar = false;
            this.bunifuTextBoxCalisanTc.WordWrap = true;
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = false;
            this.bunifuDataGridView1.AllowUserToAddRows = false;
            this.bunifuDataGridView1.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridView1.ColumnHeadersHeight = 40;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(12, 100);
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.ReadOnly = true;
            this.bunifuDataGridView1.RowHeadersVisible = false;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(396, 277);
            this.bunifuDataGridView1.TabIndex = 3;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // bunifuButtonAra
            // 
            this.bunifuButtonAra.AllowAnimations = true;
            this.bunifuButtonAra.AllowMouseEffects = true;
            this.bunifuButtonAra.AllowToggling = false;
            this.bunifuButtonAra.AnimationSpeed = 200;
            this.bunifuButtonAra.AutoGenerateColors = false;
            this.bunifuButtonAra.AutoRoundBorders = false;
            this.bunifuButtonAra.AutoSizeLeftIcon = true;
            this.bunifuButtonAra.AutoSizeRightIcon = true;
            this.bunifuButtonAra.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonAra.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonAra.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonAra.BackgroundImage")));
            this.bunifuButtonAra.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonAra.ButtonText = "ARA";
            this.bunifuButtonAra.ButtonTextMarginLeft = 0;
            this.bunifuButtonAra.ColorContrastOnClick = 45;
            this.bunifuButtonAra.ColorContrastOnHover = 45;
            this.bunifuButtonAra.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButtonAra.CustomizableEdges = borderEdges1;
            this.bunifuButtonAra.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonAra.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonAra.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonAra.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonAra.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonAra.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButtonAra.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonAra.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonAra.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonAra.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonAra.IconMarginLeft = 11;
            this.bunifuButtonAra.IconPadding = 10;
            this.bunifuButtonAra.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonAra.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonAra.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonAra.IconSize = 25;
            this.bunifuButtonAra.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonAra.IdleBorderRadius = 1;
            this.bunifuButtonAra.IdleBorderThickness = 1;
            this.bunifuButtonAra.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonAra.IdleIconLeftImage = null;
            this.bunifuButtonAra.IdleIconRightImage = null;
            this.bunifuButtonAra.IndicateFocus = false;
            this.bunifuButtonAra.Location = new System.Drawing.Point(233, 55);
            this.bunifuButtonAra.Name = "bunifuButtonAra";
            this.bunifuButtonAra.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonAra.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonAra.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonAra.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonAra.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonAra.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonAra.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonAra.OnDisabledState.IconRightImage = null;
            this.bunifuButtonAra.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonAra.onHoverState.BorderRadius = 1;
            this.bunifuButtonAra.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonAra.onHoverState.BorderThickness = 1;
            this.bunifuButtonAra.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonAra.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonAra.onHoverState.IconLeftImage = null;
            this.bunifuButtonAra.onHoverState.IconRightImage = null;
            this.bunifuButtonAra.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonAra.OnIdleState.BorderRadius = 1;
            this.bunifuButtonAra.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonAra.OnIdleState.BorderThickness = 1;
            this.bunifuButtonAra.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonAra.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonAra.OnIdleState.IconLeftImage = null;
            this.bunifuButtonAra.OnIdleState.IconRightImage = null;
            this.bunifuButtonAra.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonAra.OnPressedState.BorderRadius = 1;
            this.bunifuButtonAra.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonAra.OnPressedState.BorderThickness = 1;
            this.bunifuButtonAra.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonAra.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonAra.OnPressedState.IconLeftImage = null;
            this.bunifuButtonAra.OnPressedState.IconRightImage = null;
            this.bunifuButtonAra.Size = new System.Drawing.Size(150, 39);
            this.bunifuButtonAra.TabIndex = 1;
            this.bunifuButtonAra.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonAra.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonAra.TextMarginLeft = 0;
            this.bunifuButtonAra.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonAra.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonAra.Click += new System.EventHandler(this.bunifuButtonAra_Click);
            // 
            // bunifuButtonTumu
            // 
            this.bunifuButtonTumu.AllowAnimations = true;
            this.bunifuButtonTumu.AllowMouseEffects = true;
            this.bunifuButtonTumu.AllowToggling = false;
            this.bunifuButtonTumu.AnimationSpeed = 200;
            this.bunifuButtonTumu.AutoGenerateColors = false;
            this.bunifuButtonTumu.AutoRoundBorders = false;
            this.bunifuButtonTumu.AutoSizeLeftIcon = true;
            this.bunifuButtonTumu.AutoSizeRightIcon = true;
            this.bunifuButtonTumu.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonTumu.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonTumu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonTumu.BackgroundImage")));
            this.bunifuButtonTumu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonTumu.ButtonText = "TÜMÜ";
            this.bunifuButtonTumu.ButtonTextMarginLeft = 0;
            this.bunifuButtonTumu.ColorContrastOnClick = 45;
            this.bunifuButtonTumu.ColorContrastOnHover = 45;
            this.bunifuButtonTumu.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButtonTumu.CustomizableEdges = borderEdges2;
            this.bunifuButtonTumu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonTumu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonTumu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonTumu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonTumu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonTumu.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButtonTumu.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTumu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonTumu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonTumu.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonTumu.IconMarginLeft = 11;
            this.bunifuButtonTumu.IconPadding = 10;
            this.bunifuButtonTumu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonTumu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonTumu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonTumu.IconSize = 25;
            this.bunifuButtonTumu.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonTumu.IdleBorderRadius = 1;
            this.bunifuButtonTumu.IdleBorderThickness = 1;
            this.bunifuButtonTumu.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonTumu.IdleIconLeftImage = null;
            this.bunifuButtonTumu.IdleIconRightImage = null;
            this.bunifuButtonTumu.IndicateFocus = false;
            this.bunifuButtonTumu.Location = new System.Drawing.Point(32, 55);
            this.bunifuButtonTumu.Name = "bunifuButtonTumu";
            this.bunifuButtonTumu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonTumu.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonTumu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonTumu.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonTumu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonTumu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonTumu.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonTumu.OnDisabledState.IconRightImage = null;
            this.bunifuButtonTumu.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonTumu.onHoverState.BorderRadius = 1;
            this.bunifuButtonTumu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonTumu.onHoverState.BorderThickness = 1;
            this.bunifuButtonTumu.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonTumu.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTumu.onHoverState.IconLeftImage = null;
            this.bunifuButtonTumu.onHoverState.IconRightImage = null;
            this.bunifuButtonTumu.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonTumu.OnIdleState.BorderRadius = 1;
            this.bunifuButtonTumu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonTumu.OnIdleState.BorderThickness = 1;
            this.bunifuButtonTumu.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonTumu.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTumu.OnIdleState.IconLeftImage = null;
            this.bunifuButtonTumu.OnIdleState.IconRightImage = null;
            this.bunifuButtonTumu.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonTumu.OnPressedState.BorderRadius = 1;
            this.bunifuButtonTumu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonTumu.OnPressedState.BorderThickness = 1;
            this.bunifuButtonTumu.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonTumu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonTumu.OnPressedState.IconLeftImage = null;
            this.bunifuButtonTumu.OnPressedState.IconRightImage = null;
            this.bunifuButtonTumu.Size = new System.Drawing.Size(150, 39);
            this.bunifuButtonTumu.TabIndex = 2;
            this.bunifuButtonTumu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonTumu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonTumu.TextMarginLeft = 0;
            this.bunifuButtonTumu.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonTumu.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonTumu.Click += new System.EventHandler(this.bunifuButtonTumu_Click_1);
            // 
            // bunifuButtonCalisanCikar
            // 
            this.bunifuButtonCalisanCikar.AllowAnimations = true;
            this.bunifuButtonCalisanCikar.AllowMouseEffects = true;
            this.bunifuButtonCalisanCikar.AllowToggling = false;
            this.bunifuButtonCalisanCikar.AnimationSpeed = 200;
            this.bunifuButtonCalisanCikar.AutoGenerateColors = false;
            this.bunifuButtonCalisanCikar.AutoRoundBorders = false;
            this.bunifuButtonCalisanCikar.AutoSizeLeftIcon = true;
            this.bunifuButtonCalisanCikar.AutoSizeRightIcon = true;
            this.bunifuButtonCalisanCikar.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonCalisanCikar.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonCalisanCikar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonCalisanCikar.BackgroundImage")));
            this.bunifuButtonCalisanCikar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonCalisanCikar.ButtonText = "Çalışan Çıkar";
            this.bunifuButtonCalisanCikar.ButtonTextMarginLeft = 0;
            this.bunifuButtonCalisanCikar.ColorContrastOnClick = 45;
            this.bunifuButtonCalisanCikar.ColorContrastOnHover = 45;
            this.bunifuButtonCalisanCikar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButtonCalisanCikar.CustomizableEdges = borderEdges3;
            this.bunifuButtonCalisanCikar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonCalisanCikar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonCalisanCikar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonCalisanCikar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonCalisanCikar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonCalisanCikar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButtonCalisanCikar.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonCalisanCikar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonCalisanCikar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonCalisanCikar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonCalisanCikar.IconMarginLeft = 11;
            this.bunifuButtonCalisanCikar.IconPadding = 10;
            this.bunifuButtonCalisanCikar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonCalisanCikar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonCalisanCikar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonCalisanCikar.IconSize = 25;
            this.bunifuButtonCalisanCikar.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonCalisanCikar.IdleBorderRadius = 1;
            this.bunifuButtonCalisanCikar.IdleBorderThickness = 1;
            this.bunifuButtonCalisanCikar.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonCalisanCikar.IdleIconLeftImage = null;
            this.bunifuButtonCalisanCikar.IdleIconRightImage = null;
            this.bunifuButtonCalisanCikar.IndicateFocus = false;
            this.bunifuButtonCalisanCikar.Location = new System.Drawing.Point(233, 399);
            this.bunifuButtonCalisanCikar.Name = "bunifuButtonCalisanCikar";
            this.bunifuButtonCalisanCikar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonCalisanCikar.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonCalisanCikar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonCalisanCikar.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonCalisanCikar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonCalisanCikar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonCalisanCikar.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonCalisanCikar.OnDisabledState.IconRightImage = null;
            this.bunifuButtonCalisanCikar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonCalisanCikar.onHoverState.BorderRadius = 1;
            this.bunifuButtonCalisanCikar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonCalisanCikar.onHoverState.BorderThickness = 1;
            this.bunifuButtonCalisanCikar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonCalisanCikar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonCalisanCikar.onHoverState.IconLeftImage = null;
            this.bunifuButtonCalisanCikar.onHoverState.IconRightImage = null;
            this.bunifuButtonCalisanCikar.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonCalisanCikar.OnIdleState.BorderRadius = 1;
            this.bunifuButtonCalisanCikar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonCalisanCikar.OnIdleState.BorderThickness = 1;
            this.bunifuButtonCalisanCikar.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButtonCalisanCikar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonCalisanCikar.OnIdleState.IconLeftImage = null;
            this.bunifuButtonCalisanCikar.OnIdleState.IconRightImage = null;
            this.bunifuButtonCalisanCikar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonCalisanCikar.OnPressedState.BorderRadius = 1;
            this.bunifuButtonCalisanCikar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonCalisanCikar.OnPressedState.BorderThickness = 1;
            this.bunifuButtonCalisanCikar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonCalisanCikar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonCalisanCikar.OnPressedState.IconLeftImage = null;
            this.bunifuButtonCalisanCikar.OnPressedState.IconRightImage = null;
            this.bunifuButtonCalisanCikar.Size = new System.Drawing.Size(150, 39);
            this.bunifuButtonCalisanCikar.TabIndex = 4;
            this.bunifuButtonCalisanCikar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonCalisanCikar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonCalisanCikar.TextMarginLeft = 0;
            this.bunifuButtonCalisanCikar.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonCalisanCikar.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonCalisanCikar.Click += new System.EventHandler(this.bunifuButtonCalisanCikar_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButton1.ButtonText = "";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges4;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.IdleBorderRadius = 20;
            this.bunifuButton1.IdleBorderThickness = 15;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.IdleIconLeftImage = global::WindowsFormsApp1.Properties.Resources.back_button;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(12, 383);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 20;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 15;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.BorderRadius = 20;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 15;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnIdleState.BorderRadius = 20;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButton1.OnIdleState.BorderThickness = 15;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnIdleState.IconLeftImage = global::WindowsFormsApp1.Properties.Resources.back_button;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 20;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 15;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(55, 55);
            this.bunifuButton1.TabIndex = 17;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click_1);
            // 
            // calisanCikar
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.bunifuButton1;
            this.ClientSize = new System.Drawing.Size(420, 450);
            this.Controls.Add(this.bunifuDataGridView1);
            this.Controls.Add(this.bunifuButton1);
            this.Controls.Add(this.bunifuButtonCalisanCikar);
            this.Controls.Add(this.bunifuButtonTumu);
            this.Controls.Add(this.bunifuButtonAra);
            this.Controls.Add(this.bunifuLabelCalisanTc);
            this.Controls.Add(this.bunifuTextBoxCalisanTc);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "calisanCikar";
            this.Text = "Çalışan Çıkar";
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabelCalisanTc;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxCalisanTc;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonAra;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonTumu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonCalisanCikar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
    }
}